export default [
  { id: 'Taipei', name: '臺北市'},
  { id: 'NewTaipei', name: '新北市'},
  { id: 'Taoyuan', name: '桃園市'},
  { id: 'Taichung', name: '台中市'},
  { id: 'Tainan', name: '台南市'},
  { id: 'Kaohsiung', name: '高雄市'},
  { id: 'Keelung', name: '基隆市'},
  { id: 'Hsinchu', name: '新竹市'},
  { id: 'HsinchuCounty', name: '新竹縣'},
  { id: 'MiaoliCounty', name: '苗栗縣'},
  { id: 'ChanghuaCounty', name: '彰化縣'},
  { id: 'NantouCounty', name: '南投縣'},
  { id: 'YunlinCounty', name: '雲林縣'},
  { id: 'ChiayiCounty', name: '嘉義縣'},
  { id: 'Chiayi', name: '嘉義市'},
  { id: 'PingtungCounty', name: '屏東縣'},
  { id: 'YilanCounty', name: '宜蘭縣'},
  { id: 'HualienCounty', name: '花蓮縣'},
  { id: 'TaitungCounty', name: '臺東縣'},
  { id: 'KinmenCounty', name: '金門縣'},
  { id: 'PenghuCounty', name: '澎湖縣'},
  { id: 'LienchiangCounty', name: '連江縣'}
]